language: erlang
otp_release:
  - 17.0-rc1
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir && git checkout v0.12.5 && make && cd ..
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - MIX_ENV=test mix do deps.get
script:
  - MIX_ENV=all mix test
